baseURL = "https://nidhalsaidani.com/"
languageCode = "en-us"
title = "Nidhal Saïdani"
theme = "xmin"

[params]
  author = "Nidhal Saïdani"
    author_homepage = "https://nidhalsaidani.com"
    description = "Nidhal Saïdani's personal website"
    keywords = "Nidhal Saïdani, personal website, blog, portfolio"
    homepage = "https://nidhalsaidani.com"
    rss = "https://nidhalsaidani.com/index.xml"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    
    [[menu.main]]
        name = "Blog"
        url = "https://blog.nidhalsaidani.com/"
        weight = 2
    
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 3

    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 4

    [[menu.main]]
        name = "Now"
        url = "/now/"
        weight = 5
